MXZX/MxOnline/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
#图片资源静态路径配置
from django.views.static import serve

import xadmin
from MxOnline import settings

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    # url(r'^$',TemplateView.as_view(template_name='index.html'),name='index'),
    url(r'^user/', include('Users.urls')),
    #验证码文件url
    url(r'^captcha/', include('captcha.urls')),
    #课程机构
    url(r'^org/',include("Organization.urls")),

    #图片静态资源配置路径
    url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),

    #课程url
    url(r'^course/',include("Courses.urls")),
]

MXZX/extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

MXZX/app/Courses/models.py
from datetime import datetime

from django.db import models

from Organization.models import CourseOrg


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg,verbose_name='课程机构',null=True,blank=True)
    name = models.CharField(max_length=30,verbose_name='课程名称')
    desc = models.CharField(max_length=200,verbose_name='课程描述')
    detail = models.TextField(verbose_name='课程详情')#这是一个富文本
    degree = models.CharField(max_length=3,verbose_name='学习难度',choices=(('cj',"初级"),('zj',"中级",),('gj',"高级")),default='cj')
    learn_time = models.IntegerField(verbose_name='学习时间(分钟数)',default=0)
    students = models.IntegerField(verbose_name='学习人数',default=0)
    fav_nums = models.IntegerField(verbose_name='收藏人数', default=0)
    image = models.ImageField(max_length=100,upload_to='course/%Y/%m',verbose_name='封面图')
    click_nums = models.IntegerField(verbose_name='点击数',default=0)
    tag = models.CharField(max_length=10,verbose_name='关联课程标签',default=0)
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')

    class Meta:
        db_table='course'
        verbose_name = '学习课程'
        verbose_name_plural= verbose_name

    def __str__(self):
        return self.name

    def get_zj_nums(self):
        '''
        章节数量
        :return:
        '''
        return self.lesson_set.all().count()

    def get_learn_user(self):
        return self.usercourse_set.all()[:5]

    # def get_teacher_nums(self):
    #     return self.


class Lesson(models.Model):
    """
    学习章节
    """
    course = models.ForeignKey(Course,verbose_name='学习课程')
    name = models.CharField(max_length=20,verbose_name='章节名称')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        db_table='lesson'
        verbose_name = '学习章节'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Video(models.Model):
    lesson = models.ForeignKey(Lesson,verbose_name='学习章节')
    name = models.CharField(max_length=20, verbose_name='视频名称')
    url = models.URLField(max_length=200,verbose_name='视频地址')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        db_table = 'video'
        verbose_name = '学习视频'

        verbose_name_plural = verbose_name
    def __str__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name='学习课程')
    name = models.CharField(max_length=20, verbose_name='课程资源名称')
    download = models.FileField(upload_to='course/resource/%Y/%m',verbose_name='资源下载')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        db_table = 'course_resource'
        verbose_name = '学习资源'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

MXZX/extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

MXZX/templates/active_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户账号激活</title>
    <style>
        *{
            padding: 0;
            margin: 0;
        }
        h1{
            font-size: 30px;
            font-weight: bold;
            color: blue;
            margin: auto auto;
        }
    </style>
</head>
<body>
    <h1>用户你的{{ request.session.email }}账号已激活,请等几秒跳转登陆页面</h1>
</body>
<script>
    function login() {
    window.location.href = 'http://127.0.0.1:8000/user/login/';
    }
    window.setTimeout(login,5000);
</script>
</html>

MXZX/templates/course-detail.html
{% extends 'base.html' %}
{% block title %}公开课列表-狗几把网{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
 <section>
        <div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="/">首页</a>></li>
                <li><a href="{% url 'course_list' %}">公开课程</a>></li>
				<li>课程详情</li>
			</ul>
		</div>
	</div>
    </section>
{% endblock %}

{% block custom_content %}
<section>
	<div class="wp">
		<div class="groupPurchase_detail detail">
			<div class="toppro">
				<div class="left">
					<div class="picbox">
						<div class="tb-booth tb-pic">
							<img width="440" height="335" src="{{ MEDIA_URL }}{{ courses.image }}"  rel="{{ MEDIA_URL }}{{ courses.image }}" class="jqzoom" />
						</div>
						<ul class="tb-thumb" id="thumblist">
                            <li class="tb-selected">
                                <div class="tb-pic">
                                    <a>
                                        <img width="104" height="85" src="{{ MEDIA_URL }}{{ courses.image }}"
                                             mid="{{ MEDIA_URL }}{{ courses.image }}" big="{{ MEDIA_URL }}{{ courses.image }}">
                                    </a>
                                </div>
                            </li>
                            <li class="">
                                <div class="tb-pic">
                                    <a>
                                        <img width="104" height="85" src="{{ MEDIA_URL }}{{ courses.image }}"
                                             mid="{{ MEDIA_URL }}{{ courses.image }}" big="{{ MEDIA_URL }}{{ courses.image }}">
                                    </a>
                                </div>
                            </li>
                            <li class="">
                                <div class="tb-pic">
                                    <a>
                                        <img width="104" height="85" src="{{ MEDIA_URL }}{{ courses.image }}"
                                             mid="{{ MEDIA_URL }}{{ courses.image }}" big="{{ MEDIA_URL }}{{ courses.image }}">
                                    </a>
                                </div>
                            </li>
                            <li class="">
                                <div class="tb-pic">
                                    <a>
                                        <img width="104" height="85" src="{{ MEDIA_URL }}{{ courses.image }}"
                                             mid="{{ MEDIA_URL }}{{ courses.image }}" big="{{ MEDIA_URL }}{{ courses.image }}">
                                    </a>
                                </div>
                            </li>
						</ul>
					</div>
					<div class="des">
						<h1 title="{{ courses.name }}">{{ courses.name }}</h1>
						<span class="key">django 从入门到精通体验开始了&quot;django 从入门到精通体验开始了&quot;django 从入门到精通体验开始了：
      1. views配置
      2. url.py配置&quot;views配置&quot;views配置：
      1. views配置</span>
						<div class="prize">
							<span class="fl">价格：<i class="key">免费</i></span>
							<span class="fr">学习人数：{{ courses.students }}/span>
						</div>
						<ul class="parameter">
							<li><span class="pram word3">时&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;长：</span><span>{{ courses.learn_time }}</span></li>
                            <li><span class="pram word3">课程难度：</span><span>{{ courses.get_degree_display }}</span></li>
                            <li><span class="pram word3">课程类别：</span><span title="">免费</span></li>
							<li class="piclist"><span class="pram word4">学习用户：</span>
                                {% for learn_user in courses.get_learn_user %}
                                <span class="pic"><img width="40" height="40" src="{{ MEDIA_URL }}{{ learn_user.head_img }}"/></span>

                                {% endfor %}
							</li>
						</ul>
						<div class="btns">
							<div class="btn colectgroupbtn  notlogin
                                  "data-favid="15" id="jsLeftBtn">
                                  收藏
                            </div>
                                <div class="buy btn"><a style="color: white" href="{% url 'course_learn' courses.id %}">开始学习</a></div>
						</div>
					</div>
                    <div class="group-share-box">
                        <div class="bdsharebuttonbox"
                             data-text="django开始了"
                             data-desc="我在#慕课网#发现了"
                             data-comment=""
                             data-url="/group/groupdetail/15/">
                            <span class="fl">分享到：</span>
                            <a href="#" class="bds_more" data-cmd="more"></a>
                            <a title="分享到QQ空间" href="#" class="bds_qzone" data-cmd="qzone"></a>
                            <a title="分享到新浪微博" href="#" class="bds_tsina" data-cmd="tsina"></a>
                            <a title="分享到腾讯微博" href="#" class="bds_tqq" data-cmd="tqq"></a>
                            <a title="分享到人人网" href="#" class="bds_renren" data-cmd="renren"></a>
                            <a title="分享到微信" href="#" class="bds_weixin" data-cmd="weixin"></a>
                        </div>
                    </div>
				</div>
				<div class="right">
					<div class="head">
						<h1>授课机构</h1>
						<p>世界名校，课程权威</p>
					</div>
					<div class="pic">
                        <a href="/company/14/">
                            <img width="150" height="80" src="{{ MEDIA_URL }}{{ courses.course_org.image }}"/>
                        </a>
                    </div>
					<a href="/company/14/">
                        <h2 class="center" title="{{ courses.course_org.name }}">{{ courses.course_org.name }}</h2>
                    </a>
					<p class="center tell">电话：123123123</p>
					<div class="btn  notlogin
					     "data-favid="14" id="jsRightBtn">
                         收藏
                    </div>
					<div class="clear">
						<ul>
                            <li>
                                <span>课 &nbsp;程&nbsp; 数：&nbsp;&nbsp;世界名校</span>
                            </li>
                            <li>
                                <span>课 &nbsp;程&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   10</span>
                            </li>
                            <li>
                                <span>教 &nbsp;师&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  10</span>
                            </li>
                            <li>
                                <span>推 &nbsp;荐&nbsp; 课：&nbsp;&nbsp;django实战</span>
                            </li>
							<li>所在地区：&nbsp;&nbsp;北京市五道口</li>
							<li>认&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;证&nbsp;:
                                &nbsp;&nbsp;
								    <img title="金牌机构", src="/static/images/gold.png"/>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<section>
	<div class="wp">
		<div class="list groupPurchase_detail_pro">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="active">产品详细</li>
					</ul>
				</div>
				<div class="tab_cont tab_cont1">
					<p><img src="{{ MEDIA_URL }}{{ courses.image }}" title="" alt="blob.png"/> </p><p><img src="{{ MEDIA_URL }}{{ courses.image }}" title="" alt="blob.png"/> </p><p><img src="{{ MEDIA_URL }}{{ courses.image }}" title="" alt="blob.png"/> </p><p><img src="{{ MEDIA_URL }}{{ courses.image }}" title="" alt="blob.png"/> </p><p><img src="{{ MEDIA_URL }}{{ courses.image }}" title="" alt="blob.png"/> </p>
				</div>
				<div class="tab_cont tab_cont2" >
					<div class="comment">
						<div class="comenlist">

	                    </div>
					</div>
				</div>
			</div>
			<div class="right layout">
				<div class="head">相关课程推荐</div>

			</div>
		</div>
	</div>
</section>
{% endblock %}

MXZX/templates/course-list.html
{% extends 'base.html' %}
{% block title %}公开课列表-狗几把网{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
 <section>
<div class="wp">
		<ul  class="crumbs">
            <li><a href="/">首页</a>></li>
			<li><a href="{% url 'course_list' %}">公开课</a>></li>
			<li>课程首页</li>
		</ul>
	</div>
    </section>
{% endblock %}

{% block custom_content %}
<section>
	<div class="wp">
		<div class="list" style="margin-top:0;">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li {% ifequal sort '' %}class="active"{% endifequal %}><a href="?sort=&hot=">最新 </a></li>
						<li {% ifequal sort 'hot' %}class="active"{% endifequal %}><a href="?sort=hot">最热门</a></li>
						<li {% ifequal sort 'sort' %}class="active"{% endifequal %}><a href="?sort=sort">参与人数</a></li>
					</ul>
				</div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
					<div class="group_list">
                    {% for course in all_courses.object_list %}
                            <div class="box">
                                <a href="{% url 'course_detail' course.id %}">
                                    <img width="280" height="350" class="{{ MEDIA_URL }}{{ course.image }}" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course_detail' course.id %}">
                                        <h2>{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{ course.learn_time }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}&nbsp;&nbsp;</span>
                                </div>
                                <div class="bottom">
                                    <a href="{% url 'course_detail' course.id %}"><span class="fl">来自{{ course.course_org.name }}</span></a>
                                    <span class="star fr  notlogin
                                        " data-favid="15">
                                        {{ course.fav_nums }}
                                    </span>
                                </div>
                            </div>
                    {% endfor %}
					</div>
                    <div class="pageturn">
                        <ul class="pagelist">
                                        {% if all_courses.has_previous %}
                    <li class="long"><a href="?{{ all_courses.previous_page_number.querystring }}">上一页</a></li>
                {% endif %}

                {% for page in all_courses.pages %}
                    {% if page %}
                        {% ifequal page all_courses.number %}
                            <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                        {% else %}
                            <li class="page"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                        {% endifequal %}
                    {% else %}
                            <li><a href="" class="none">...</a></li>
                    {% endif %}
                {% endfor %}
                {% if all_courses.has_next %}
                    <li class="long"><a href="?{{ all_courses.next_page_number.querystring }}">下一页</a></li>
                {% endif %}
                        </ul>
                    </div>
				</div>
                </div>
			</div>
			<div class="right layout">
				<div class="head">热门课程推荐</div>
				<div class="group_recommend">

                    {% for hot in hot_courses %}
					<dl>
						<dt>
							<a target="_blank" href="{{ ecmall_ad.url }}">
								<img width="240" height="220" class="scrollLoading" data-url="{{ MEDIA_URL }}{{ hot.image }}" src="{{ MEDIA_URL }}{{ hot.image }}"/>
							</a>
						</dt>
						<dd>
							<a target="_blank" href="{{ ecmall_ad.url }}"><h2>{{ hot.name }}</h2></a>
							<span class="fl">优惠价：<i class="key">￥200</i></span>
						</dd>
					</dl>
                    {% endfor %}
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

MXZX/templates/org-detail-teachers.html
{% extends 'home.html' %}
{% block title %}机构教师{% endblock %}
{% block right%}
    <div class="right companycenter layout">
        <div class="head">
            <h1>机构教师</h1>
            <a class="green fr more" href="org-detail-teachers.html">查看更多 > </a>
        </div>
        {% for teacher in all_teachers %}
            <div class="diarys">
            <div class="module5 share company-diary-box" style="padding:10px 0;">
                <div class="left">
                    <img class="pic" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                    <p>昵称：{{ teacher.name }}</p>
                </div>
                <div class="right">
                    <div class="top">
                        <div class="fl">
                            <a href=""><h1>{% for course in all_courses %}{{ course.name }}{% endfor %}</h1></a>
                            <span>发表于：{{ teacher.add_time }}</span>
                        </div>
                    </div>
                    <div class="middle" style="border-bottom:0;">{{ course_org.desc }}</div>
                </div>
            </div>
        </div>
        {% endfor %}



    </div>
{% endblock %}

MXZX/templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="{% static '/css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <style>
        .error {
            background: #fb8344 none repeat scroll 0 0;
            color: #fff !important;
            line-height: 40px !important;
            margin: 10px 0;
            text-align: center;
            width: 200px;
        }
    </style>

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="{% url 'user_modify' %}" method="POST">
            <ul>
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password1" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <input type="hidden" name="email" value="{{ email }}">
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <div class="error btns" id="jsForgetTips">{% for k,v in reset_form.errors.items %}{{ v }}{% endfor %}</div>
                <li class="button">
                    <input type="submit" value="提交" >
                </li>
            </ul>
            {% csrf_token %}
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="/static/images/check2.png">
        <p class="successword">已经成功修改密码，请<a href="{% url 'user_login' %}">重新登录</a></p>
    </div>
</div>
</body>
</html>